request = {
'_charset': 'utf-8',
'_encoding_errors': 'replace',
'_url_charset': 'utf-8',
'method': 'POST',
'scheme': 'http',
'server': ('0.0.0.0', 8000), 'root_path': '',
'path': '/api/method/frappe.sessions.clear',
'query_string': b'',
'headers': [
	('X-Forwarded-For', '10.0.1.23'),
	('X-Forwarded-Proto', 'http'),
	('X-Frappe-Site-Name', 'comomejorar.info'),
	('Host', 'comomejorar.info'),
	('X-Use-X-Accel-Redirect', 'True'),
	('Connection', 'close'),
	('Content-Length', '0'),
	('X-Real-Ip', '88.8.117.159'),
	('X-Real-Ip-Dfp', '88.8.117.159'),
	('Sec-Ch-Ua', '"Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"'),
	('X-Frappe-Csrf-Token', '642107b8d60a882b157ca1b6f34e5c2ca71cd64919663c76ec813ae3'),
	('Sec-Ch-Ua-Mobile', '?0'),
	('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'),
	('Accept', 'application/json'),
	('X-Requested-With', 'XMLHttpRequest'),
	('X-Frappe-Cmd', ''),
	('Sec-Ch-Ua-Platform', '"Linux"'),
	('Sec-Gpc', '1'),
	('Origin', 'https://comomejorar.info'),
	('Sec-Fetch-Site', 'same-origin'),
	('Sec-Fetch-Mode', 'cors'),
	('Sec-Fetch-Dest', 'empty'),
	('Referer', 'https://comomejorar.info/app/error-log'),
	('Accept-Encoding', 'gzip, deflate, br'),
	('Accept-Language', 'es,en;q=0.9'),
	('Cookie', 'sid=c5babdbd9db2d0ce49818890956b9eed634e0247d3cac35c4ba59ab4; system_user=yes; full_name=Administrator; user_id=Administrator; user_image=')
],
'remote_addr': '10.0.1.23',
'environ': {
	'wsgi.errors': '<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f0ff7b6a350>',
	'wsgi.version': (1, 0),
	'wsgi.multithread': True,
	'wsgi.multiprocess': True,
	'wsgi.run_once': False,
	'wsgi.file_wrapper': "<class 'gunicorn.http.wsgi.FileWrapper'>",
	'wsgi.input_terminated': True,
	'SERVER_SOFTWARE': 'gunicorn/21.2.0',
	'wsgi.input': '<gunicorn.http.body.Body object at 0x7f0ff77c0050>',
	'gunicorn.socket': "<socket.socket fd=10, family=2, type=1, proto=0, laddr=('10.0.1.84', 8000), raddr=('10.0.1.23', 36930)>",
	'REQUEST_METHOD': 'POST',
	'QUERY_STRING': '',
	'RAW_URI': '/api/method/frappe.sessions.clear',
	'SERVER_PROTOCOL': 'HTTP/1.1',
	'HTTP_X_FORWARDED_FOR': '10.0.1.23',
	'HTTP_X_FORWARDED_PROTO': 'http',
	'HTTP_X_FRAPPE_SITE_NAME': 'comomejorar.info',
	'HTTP_HOST': 'comomejorar.info',
	'HTTP_X_USE_X_ACCEL_REDIRECT': 'True',
	'HTTP_CONNECTION': 'close',
	'CONTENT_LENGTH': '0',
	'HTTP_X_REAL_IP': '88.8.117.159',
	'HTTP_X_REAL_IP_DFP': '88.8.117.159',
	'HTTP_SEC_CH_UA': '"Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
	'HTTP_X_FRAPPE_CSRF_TOKEN': '642107b8d60a882b157ca1b6f34e5c2ca71cd64919663c76ec813ae3',
	'HTTP_SEC_CH_UA_MOBILE': '?0',
	'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
	'HTTP_ACCEPT': 'application/json',
	'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
	'HTTP_X_FRAPPE_CMD': '',
	'HTTP_SEC_CH_UA_PLATFORM': '"Linux"',
	'HTTP_SEC_GPC': '1',
	'HTTP_ORIGIN': 'https://comomejorar.info',
	'HTTP_SEC_FETCH_SITE': 'same-origin',
	'HTTP_SEC_FETCH_MODE': 'cors',
	'HTTP_SEC_FETCH_DEST': 'empty',
	'HTTP_REFERER': 'https://comomejorar.info/app/error-log',
	'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
	'HTTP_ACCEPT_LANGUAGE': 'es,en;q=0.9',
	'HTTP_COOKIE': 'sid=c5babdbd9db2d0ce49818890956b9eed634e0247d3cac35c4ba59ab4; system_user=yes; full_name=Administrator; user_id=Administrator; user_image=',
	'wsgi.url_scheme': 'http',
	'REMOTE_ADDR': '10.0.1.23',
	'REMOTE_PORT': '36930',
	'SERVER_NAME': '0.0.0.0',
	'SERVER_PORT': '8000',
	'PATH_INFO': '/api/method/frappe.sessions.clear',
	'SCRIPT_NAME': '',
	'werkzeug.request': "<Request 'http://comomejorar.info/api/method/frappe.sessions.clear' [POST]>"
},
'shallow': False,
'after_response': "<frappe.utils.CallbackManager object at 0x7f0ff7b68580>",
'max_content_length': 10485760,
'stream': "<werkzeug.wsgi.LimitedStream object at 0x7f0ff7829810>",
'_cached_data': b'',
'args': "ImmutableMultiDict([])",
'form': "ImmutableMultiDict([])",
'files': "ImmutableMultiDict([])",
'cookies': ImmutableMultiDict([
	('sid', 'c5babdbd9db2d0ce49818890956b9eed634e0247d3cac35c4ba59ab4'),
	('system_user', 'yes'),
	('full_name', 'Administrator'),
	('user_id', 'Administrator'),
	('user_image', '')]),
'host': 'comomejorar.info',
'url': 'http://comomejorar.info/api/method/frappe.sessions.clear'
}
